### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by ayushrox** [YunanZhu/Pytorch-TestRankIQA#4]
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    main(parser.parse_args())
  File "main.py", line 51, in main
    x, y = img.shape[0], img.shape[1]
IndexError: tuple index out of range

**Comment by YunanZhu** [comment]
Make sure that you read an image (using "cv2.imread").
If "img" is the result of reading an RGB image, its shape will be [height, width, 3].

**Comment by ayushrox** [comment]
thanks for the reply!

` img = cv2.imread(opt.test_set + files[i])`
            `img = np.asarray(img)`
            `x, y = img.shape[0], img.shape[1]`

This is the specific code in main.py 
the image is RGB from the LIVE dataset, what should I do?

**Comment by YunanZhu** [comment]
Check the info of Sec. [Getting Started](https://github.com/YunanZhu/Pytorch-TestRankIQA#getting-started).

I think you can use either of following commands:
1. `python main.py --test_set "ur_path/LIVE2/" --model_file "./pre-trained/Rank_live.caffemodel.pt" --test_file "./data/ft_live_test.txt" --res_file "./result.csv"`
2. `python main.py --test_set "ur_path/LIVE2/" --model_file "./pre-trained/FT_live.caffemodel.pt" --test_file "./data/ft_live_test.txt" --res_file "./result.csv"`

**Please make sure your LIVE2 dataset is at "ur_path/LIVE2/".**

First, check your LIVE2 dataset folder, `"ur_path/LIVE2/"`.
There will be 6 sub-folders ("refimgs", "fastfading", "gblur", "jp2k", "jpeg" and "wn") in it.

Second, you need to generate a txt file as `"--test_file"`, or just use the txt file I given: ["./data/ft_live_test.txt"](https://github.com/YunanZhu/Pytorch-TestRankIQA/blob/main/data/ft_live_test.txt).
You can see the format of this txt file. There are 2 components in each line, the first one is the image, the second one is the MOS (ground-truth).
For example, the first line is `"/gblur/img120.bmp  66.07"`. Make sure that `"ur_path/LIVE2/" + "/gblur/img120.bmp"` can point to this image file correctly.

**Comment by YunanZhu** [comment]
If you just want to get the predicted score of an image.

You can simply use the following code:
```
# Check the state of GPU.
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")
print("cuda state: " + "available" if use_cuda else "unavailable")

net = Vgg16()
net.load_model("./pre-trained/FT_live.caffemodel.pt")  # The pre-trained model file is necessary.
net.to(device)
net.eval()

# Start to test.
Num_Patch = 30  # random crop patches "Num_Patch" times
pred = 0.0
feat = np.zeros(shape=Num_Patch)  # Just used to calculate the median of all patch scores.
with torch.no_grad():
    # Load image file.
    img = cv2.imread(r"E:\Resources\datasets\LIVE2\fastfading/img1.bmp")  # Give your image file here.
    img = np.asarray(img)
    x, y = img.shape[0], img.shape[1]

    # Crop patches & calculate pred scores.
    for j in range(Num_Patch):
        x_p = np.random.randint(x - 224)
        y_p = np.random.randint(y - 224)
        patch = img[x_p:(x_p + 224), y_p:(y_p + 224), :].transpose([2, 0, 1])
        patch = torch.from_numpy(patch).unsqueeze(dim=0).float().to(device)
        # this network can only accept size(224x224) patch
        score = net(patch)

        feat[j] = score.item()
        pred += score.item()

    pred /= Num_Patch  # average
    medn = np.median(feat[:])

    print(f"Predicted score: {pred} | Median: {medn}")
```

**Comment by YunanZhu** [comment]
If you just want to get the predicted score of an image.
You can simply use the following code:

```
# Check the state of GPU.
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")
print("cuda state: " + "available" if use_cuda else "unavailable")

net = Vgg16()
net.load_model("./pre-trained/FT_live.caffemodel.pt")  # The pre-trained model file is necessary.
net.to(device)
net.eval()

# Start to test.
Num_Patch = 30  # random crop patches "Num_Patch" times
pred = 0.0
feat = np.zeros(shape=Num_Patch)  # Just used to calculate the median of all patch scores.
with torch.no_grad():
    # Load image file.
    img = cv2.imread(r"your_path/your_image.bmp")  # Give your image file here.
    img = np.asarray(img)
    x, y = img.shape[0], img.shape[1]

    # Crop patches & calculate pred scores.
    for j in range(Num_Patch):
        x_p = np.random.randint(x - 224)
        y_p = np.random.randint(y - 224)
        patch = img[x_p:(x_p + 224), y_p:(y_p + 224), :].transpose([2, 0, 1])
        patch = torch.from_numpy(patch).unsqueeze(dim=0).float().to(device)
        # this network can only accept size(224x224) patch
        score = net(patch)

        feat[j] = score.item()
        pred += score.item()

    pred /= Num_Patch  # average
    medn = np.median(feat[:])

    print(f"Predicted score: {pred} | Median: {medn}")
```
